<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7184d871-9382-4a31-ac9a-123cd9296d2c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
