<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>9217ec39-2206-4ba5-9769-abc3671e5c5d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set Order to a new order ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
