<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>11a5f4f3-43c0-4a96-9262-6ae6704837ee</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
