<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Number of Months Since Most Recent Face to Face Examination</name>
  <uuid>43289fdf-3b08-4437-96a2-e84663853c45</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the face to face examination date of 'Medical Record' is not null
	and the run date of System is not null
then
	set decision to the number of months between the run date of System and the face to face examination date of 'Medical Record';
else
    set decision to 0;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
