<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>207e3496-6e1a-4899-8b69-964fa357d7ec</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
