<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>63785a60-70de-4340-b430-f8c930974084</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Approved ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
