<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>2f4ea0b4-3f4f-4beb-b600-5d9eb6c9ab72</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Other ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
