<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>test</name>
  <uuid>c40a3395-b4cf-4515-b7a1-0c0e6d4686d1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision  to the sum of 'Primary Count'  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
