<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1e1f34ff-b484-42ce-b7b3-42790f34ce67</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Valid ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
