<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>f0b63b4f-38ae-43db-9116-cc51c0982aa3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set Dummy to "" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
