<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Number of Weeks Since Last Girth Measurements</name>
  <uuid>1f16eb97-97ae-41c0-886a-74e2daf89e10</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the girth measurement date of Demo is not null and  the run date of System is not null
then
	set decision to the number of weeks between the girth measurement date of Demo and the run date of System ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
