<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>27fced86-db2e-441d-800c-b5d2aa088467</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
