<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>9212c11d-7839-4812-a0ed-7c3bb6d64f62</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the patient responsibility amount of  'Verification of Benefits' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
