<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f21d2415-89f8-4a11-9d4a-8c007a79261c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Match ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
