<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>f6e60213-1eed-4a46-8cfb-c96e4e8791e3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'SMN LMN' to a new SMNLMN;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
