<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>d33aad14-8e8c-4bd5-8a32-8c7b80750301</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Acceptable ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
