<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>56e15ed8-8933-48e0-b146-3c191924411d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set Document to a new document;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
