<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>9800e5a5-1571-4c2b-96f0-e9cf424fe76f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Other" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
