<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>5938c457-38bd-4c32-a224-3e6307c29f0a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 12/23/2024 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
