<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>061a9bc7-ed52-47a3-8dad-64b94dfb3e10</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Valid ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
