<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>test</name>
  <uuid>867f588e-7c68-47ed-ab09-3d9aa374994b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each Primary/Not Primary , in 'Primary Plan Indicator' 
if 
	this Primary/Not Primary is Primary then 
    add 1  to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
