<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>24efae44-7eda-4635-9267-9df6950d3f43</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Entre ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
