<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>679f28ce-03cb-4a20-9ef9-50e029516066</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Match ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
