<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>df9a52b4-b93b-4a98-87bd-aeb195bc6c5d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set Prescription to a new prescription ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
