<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>3ef343a0-1108-4523-b46d-e2de12310f78</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new payer requirements where
		
		the diagnosis acceptability list is "CVU" , 
		the diet and medication evaluation required is Required , 
		the medical records on file required is Required,
        
	the SMN/LMN on file required is Required ;
    print "test";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
