<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f72b5ec4-c05c-46cf-b870-fec3ee676781</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Match ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
