<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>85ff74b0-661d-4a74-94a1-b89267f606bc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Not Required ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
