<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>7c464b50-85db-4605-acb1-37d06d8444d9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'SMN LMN' to a new SMNLMN ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
